apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaboom-games-deployment
  labels:
    app: kaboom-games
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kaboom-games
  template:
    metadata:
      labels:
        app: kaboom-games
    spec:
      containers:
      - name: kaboom-games
        image: toleksa/kaboom-games
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: kaboom-games-service
spec:
  selector:
    app: kaboom-games
  type: LoadBalancer
  #loadBalancerIP: 192.168.0.238
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: kaboom-games-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: kaboom.kube.ac
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: kaboom-games-service
            port: 
              number: 80
